# Generated by Django 5.0.3 on 2024-04-08 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalhistory',
            name='idDoctor',
            field=models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='idOrder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order'),
        ),
        migrations.AlterField(
            model_name='clinicalhistory',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='idMedicalAppointment',
            field=models.ForeignKey(db_column='idMedicalAppointment', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medicalappointment'),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='idDoctor',
            field=models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee'),
        ),
        migrations.AlterField(
            model_name='medicalappointment',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
        migrations.AlterField(
            model_name='medicalinsurance',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='idDoctor',
            field=models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
        migrations.AlterField(
            model_name='orderhelpdiagnostic',
            name='idOrder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order'),
        ),
        migrations.AlterField(
            model_name='ordermedication',
            name='idMedication',
            field=models.ForeignKey(db_column='idMedication', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medication'),
        ),
        migrations.AlterField(
            model_name='ordermedication',
            name='idOrder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order'),
        ),
        migrations.AlterField(
            model_name='orderprocedure',
            name='idOrder',
            field=models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order'),
        ),
        migrations.AlterField(
            model_name='orderprocedure',
            name='idProcedure',
            field=models.ForeignKey(db_column='idProcedure', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.procedure'),
        ),
        migrations.AlterField(
            model_name='orderprocedureassistance',
            name='idOrderProcedure',
            field=models.ForeignKey(db_column='idOrderProcedure', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.orderprocedure'),
        ),
        migrations.AlterField(
            model_name='vitaldata',
            name='idPatient',
            field=models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient'),
        ),
    ]
