# Generated by Django 5.0.3 on 2024-04-15 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('bornDate', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=200)),
                ('rol', models.CharField(max_length=30)),
                ('userName', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('dosage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('idDocument', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('bornDate', models.CharField(max_length=80)),
                ('genre', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=80)),
                ('idDoctor', models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee')),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idMedicalAppointment', models.ForeignKey(db_column='idMedicalAppointment', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medicalappointment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDoctor', models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee')),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHelpDiagnostic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameHelpDiagnostic', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('amount', models.FloatField()),
                ('item', models.IntegerField()),
                ('idOrder', models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderMedication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dose', models.FloatField()),
                ('treatmentDuration', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('item', models.IntegerField()),
                ('idMedication', models.ForeignKey(db_column='idMedication', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.medication')),
                ('idOrder', models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcedure',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('frequency', models.CharField(max_length=100)),
                ('item', models.IntegerField()),
                ('idOrder', models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order')),
                ('idProcedure', models.ForeignKey(db_column='idProcedure', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.procedure')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcedureAssistance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idSpecialist', models.CharField(max_length=255)),
                ('idOrderProcedure', models.ForeignKey(db_column='idOrderProcedure', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.orderprocedure')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalInsurance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameOfInsuranceCompany', models.CharField(max_length=255)),
                ('policyNumber', models.BigIntegerField()),
                ('policyState', models.BooleanField()),
                ('policyValidity', models.CharField(max_length=80)),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('consultReason', models.CharField(max_length=255)),
                ('symptomatology', models.CharField(max_length=255)),
                ('diagnosis', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=80)),
                ('idDoctor', models.ForeignKey(db_column='idDoctor', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.employee')),
                ('idOrder', models.ForeignKey(db_column='idOrder', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.order')),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VitalData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arterialPressure', models.FloatField()),
                ('temperature', models.FloatField()),
                ('pulse', models.IntegerField()),
                ('bloodOxygenLevel', models.FloatField()),
                ('idPatient', models.ForeignKey(db_column='idPatient', on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.patient')),
            ],
        ),
    ]
